podcast/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.episode_list, name='episode_list'),
    url(r'^episode/(?P<slug>[\w\-]+)$', views.EpisodeView.as_view(), name='episode'),
    url(r'^episodes$', views.episode_list, name='episode_list'),
]

podcast_site/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
    url(r'^podcast/', include('podcast.urls', namespace='podcast')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

podcast/models.py
from django.db import models
from django.template.defaultfilters import slugify

import re
import string


class Episode(models.Model):
    posted_by = models.ForeignKey('auth.User')
    title = models.CharField(max_length=100)
    audio_file = models.FileField(upload_to='episodes/')
    description = models.TextField(max_length=10000)
    publish_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True)

    class Meta:
        ordering = ['-publish_date']

    def save(self, **kwargs):
        slug_str = '%s' % self.title
        unique_slugify(self, slug_str.lower())
        super(Episode, self).save(**kwargs)

    def short_description(self, max_length=100):
        """Returns the beginning of the episode's descriptions."""
        if len(self.description) <= max_length:
            return self.description
        s = ''
        d = self.description.split()
        while len(s) < max_length:
            s += d.pop(0) + ' '
        s = s.strip() + '...'
        return s

    def __str__(self):
        return '%s' % self.title


def unique_slugify(instance, value, slug_field_name='slug', queryset=None,
                   slug_separator='-'):
    """
    Calculates and stores a unique slug of ``value`` for an instance.

    ``slug_field_name`` should be a string matching the name of the field to
    store the slug in (and the field to check against for uniqueness).

    ``queryset`` usually doesn't need to be explicitly provided - it'll default
    to using the ``.all()`` queryset from the model's default manager.
    """
    slug_field = instance._meta.get_field(slug_field_name)

    slug = getattr(instance, slug_field.attname)
    slug_len = slug_field.max_length

    # Sort out the initial slug, limiting its length if necessary.
    slug = slugify(value)
    if slug_len:
        slug = slug[:slug_len]
    slug = _slug_strip(slug, slug_separator)
    original_slug = slug

    # Create the queryset if one wasn't explicitly provided and exclude the
    # current instance from the queryset.
    if queryset is None:
        queryset = instance.__class__._default_manager.all()
    if instance.pk:
        queryset = queryset.exclude(pk=instance.pk)

    # Find a unique slug. If one matches, at '-2' to the end and try again
    # (then '-3', etc).
    next = 2
    while not slug or queryset.filter(**{slug_field_name: slug}):
        slug = original_slug
        end = '%s%s' % (slug_separator, next)
        if slug_len and len(slug) + len(end) > slug_len:
            slug = slug[:slug_len-len(end)]
            slug = _slug_strip(slug, slug_separator)
        slug = '%s%s' % (slug, end)
        next += 1

    setattr(instance, slug_field.attname, slug)


def _slug_strip(value, separator='-'):
    """
    Cleans up a slug by removing slug separator characters that occur at the
    beginning or end of a slug.

    If an alternate separator is used, it will also replace any instances of
    the default '-' separator with the new separator.
    """
    separator = separator or ''
    if separator == '-' or not separator:
        re_sep = '-'
    else:
        re_sep = '(?:-|%s)' % re.escape(separator)
    # Remove multiple instances and if an alternate separator is provided,
    # replace the default '-' separator.
    if separator != re_sep:
        value = re.sub('%s+' % re_sep, separator, value)
    # Remove separator from the beginning and end of the slug.
    if separator:
        if separator != '-':
            re_sep = re.escape(separator)
        value = re.sub(r'^%s+|%s+$' % (re_sep, re_sep), '', value)
    return value

podcast/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views import generic

from .models import Episode

def index(request):
    return render(request, 'blog/index.html')

def episode_list(request):
    episodes = Episode.objects.all()
    context = { 'episodes': episodes }
    return render(request, 'podcast/episode_list.html', context=context)

class EpisodeView(generic.DetailView):
    model = Episode

podcast_site/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views import generic

from podcast import models

# Returns 5 most recent episodes for context
def home_page(request):
    episodes = get_episode_list()
    context = { 'episodes': episodes[0:5] }
    return render(request, 'home.html', context=context)


def get_episode_list():
    episodes = models.Episode.objects.all()
    return episodes

podcast/templates/podcast/episode_detail.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static "css/episode-styling.css" %}" type="text/css" />
<link rel="stylesheet" href="{% static "podcast/css/episode-detail.css" %}" type="text/css" />
{% endblock %}

{% block content %}
<body>
    <div class="episode-container">
        <h2 class="episode-title">{{ episode.title|safe }}</h2>

        {% include "audio-player.html" %}

        <!-- Wrap content in <pre> to allow whitespace  -->
        <pre class="episode-content-pre">
            <p class="episode-content">{{ episode.description|safe }}</p>
        </pre>
        <p class="episode-date">
            {{ episode.publish_date|date:"l, F d, Y" }}
        </p>
    </div>

</body>
{% endblock %}

{% block scripts %}
<script src="https://d3js.org/d3.v3.min.js"></script>
<script src="{% static "podcast/js/player.js" %}" type="text/javascript" ></script>
{% endblock %}

podcast/templates/podcast/episode_list.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static "css/home-page.css" %}" type="text/css" />
<link rel="stylesheet" href="{% static "css/episode-styling.css" %}" type="text/css" />
{% endblock %}

{% block content %}
<body>
    <div class="episode-list">
        <h2 class="category-header">All episodes</h2>
        {% for episode in episodes %}
        <div class="episode-summary">
            <h3 class="episode-title">
                <a class="nostyle" href="{% url 'podcast:episode' slug=episode.slug %}">{{ episode.title }}</a>
            </h3>
            <p class="episode-date">{{ episode.publish_date|date:"l, F d, Y" }}</p>
        </div>
        {% endfor %}
    </div>
</body>
{% endblock %}

templates/audio-player.html
<div id="player-container">
    <!-- Audio source -->
    <audio id="player-audio">
        <source src="{{ episode.audio_file.url }}" />
    </audio>

    <!--  Play/pause button animated with SVG -->
    <button class="play-button js-button">
        <svg width="100%" height="100%" viewBox="0 0 16 16">
            <defs>
                <path id="pause-icon" data-state="playing" d="M1,0 L7,0 7,16 1,16 M10,0 L16,0 16,16 10,16" />
                <path id="play-icon"  data-state="paused"  d="M1,0 L8,3.74 8,12.28 1,16 M8,3.74 L16,8 16,8 8,12.28" />
            </defs>
            <use xlink:href="#play-icon" />
        </svg>
    </button>

    <!-- Seeker input range to change playback position -->
    <div class="player-seeker">
        <input type="range" id="seeker-input" min="0" max="1" step="0.001" value="0" />
        <canvas id="seeker-canvas">
            Looks like <code>canvas</code> isn't supported in your browser. Try a new one. :)
        </canvas>
    </div>

    <!-- Popup to display current time of audio when seeking -->
    <div id="seeker-status">
        <p id="seeker-status-text">a / b</p>
        <div class="arrow-down"></div>
    </div>
</div>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en-US">
    <head>
        <!-- Meta       -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Beginning of content       -->
        {% block title %}<title>The Awesome Podcast</title>{% endblock %}

        <link rel="stylesheet" href="{% static "css/base-styles.css" %}" type="text/css" />
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <div id="site">
            <header>
                <nav id="menu">
                    <ul>
                        <li><a class="menu-a" href="{% url 'home_page' %}">home</a></li>
                        <li><a class="menu-a" href="{% url 'podcast:episode_list' %}">episodes</a></li>
                        <li><a class="menu-a" href="#">art</a></li>
                        <li><a class="menu-a" href="#">music</a></li>
                        <li><a class="menu-a" href="#">subscribe</a></li>
                    </ul>
                </nav>

                <div class="menu-toggle">
                    <a class="menu-a is-active" href="#menu" id="menu-open">Menu</a>
                    <a class="menu-a" href="#" id="menu-close">Close</a>
                </div>

                <h1 class="podcast-title title"><a class="nostyle" href="{% url 'home_page' %}"
                                             title="Accountability Hour">The Awesome Podcast</a></h1>
            </header>



            <section id="content">
            {% block content %}{% endblock %}
            </section>

            <section id="footer">
            {% block footer %}{% endblock %}
            </section>
        </div>
    </body>

    <script src="{% static "js/responsive.js" %}" type="text/javascript"></script>
    {% block scripts %}{% endblock %}
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static "css/home-page.css" %}" type="text/css" />
<link rel="stylesheet" href="{% static "css/episode-styling.css" %}" type="text/css" />
{% endblock %}

{% block content %}
<body>
<section class="home-container">
    <div class="episode-list">
        {% for episode in episodes %}
        <!-- Main / most recent / featured episode  -->
        {% if forloop.counter == 1 %}
        <div class="episode-summary">
            <h2 class="episode-title">
                <a class="nostyle" href="{% url 'podcast:episode' slug=episode.slug %}">{{ episode.title }}</a>
            </h2>

            <p>{{ episode.short_description|safe }}</p>
            {% include "audio-player.html" %}
        </div>

        <!-- Not most recent: list title -->
        {% else %}
        <div class="episode-summary">
            <h3 class="episode-title">
                <a class="nostyle" href="{% url 'podcast:episode' slug=episode.slug %}">{{ episode.title }}</a>
            </h3>
            <p class="episode-date">{{ episode.publish_date|date:"l, F d, Y" }}</p>
        </div>
        {% endif %}
        {% endfor %}
    </div>

    <div class="about">
        <p><strong>The Awesome Podcast</strong> is an awesome podcast, due to the awesome nature of the contents found within.</p>
        <p>It all started once when the podcast was made. Who knew then what insidious yet intensely excellent tidings the future would hold? I grow old, I grow old; I shall wear the bottoms of my trousers rolled.</p>
    </div>
</section>
</body>
{% endblock %}

{% block scripts %}
<script src="https://d3js.org/d3.v3.min.js"></script>
<script src="{% static "podcast/js/player.js" %}" type="text/javascript"></script>
{% endblock %}